// CalendarData.js — 30-day rolling content plan.
// Cadence: 1 LINE carousel push / week + 2 IG feed posts / week +
//          1 IG story / day (curated) + 1 Threads thought / week
//          + 1 TikTok cover / fortnight.
// Each entry: { day, weekday, channel, format, theme, copy, asset, ctaText }
// Channel codes: LINE | IG | IG-STORY | THREADS | TIKTOK

window.CONTENT_CALENDAR = {
  startDate: '2026-03-02',  // Mon
  weeks: 4,
  cadenceNote: '每週節奏 — 一 (LINE 主推)・三 (IG 入駐故事)・五 (IG 客戶聲音)・週末 (慢內容)',

  themes: [
    { id: 'W1', label: 'WEEK 1', name: '只要你願意說',  sub: 'OPENING · 自我介紹週',  focus: '建立信任感、解釋我們的存在意義' },
    { id: 'W2', label: 'WEEK 2', name: '誰已經來了',    sub: 'PORTFOLIO · 入駐曝光週', focus: '把本月入駐的 4 個品牌依序介紹' },
    { id: 'W3', label: 'WEEK 3', name: '我們做了什麼',  sub: 'PROCESS · 過程透明週',  focus: '展示「好物・好照」「陪你被看見」的實際工序' },
    { id: 'W4', label: 'WEEK 4', name: '下一個會是誰',  sub: 'INVITATION · 招募下一批', focus: '收尾與開放下一波諮詢' },
  ],

  entries: [
    // ===== WEEK 1 — 只要你願意說 =====
    { day: 1, weekday: '一', week: 'W1', channel: 'LINE', format: 'Carousel Push', theme: 'opening',
      title: '本月入駐 · 4 件作品',
      copy: '本月入駐的 4 個品牌，從一個攤位、一間店、一個老字號、一段新合作。\n往右滑，看他們是誰。',
      asset: '4 cards (1040×1040 ea.)',
      cta: '回「01 / 02 / 03 / 04」看單一案例' },
    { day: 2, weekday: '二', week: 'W1', channel: 'IG-STORY', format: 'Story', theme: 'opening',
      title: '只要你願意說',
      copy: '我們是 3Q貢丸 ── 台灣在地品牌孵化所。\n從 10 元的茶葉蛋，到上市的企業，我們都把你當客人接。',
      asset: 'cupped-palm-light.svg (1080×1920)',
      cta: 'tap to LINE @121LKSPE' },
    { day: 3, weekday: '三', week: 'W1', channel: 'IG', format: 'Feed (4:5)', theme: 'opening',
      title: 'NO. 01 · 阿婆ㄟ切仔麵店',
      copy: '雲林。三十二年。從一張矮桌起家。\n本月入駐 ── 第一件事，是把那碗看了三十年的麵，重新拍一次。',
      asset: 'still-bowl-rice.svg (1080×1350)',
      cta: 'see more →' },
    { day: 4, weekday: '四', week: 'W1', channel: 'IG-STORY', format: 'Story', theme: 'opening',
      title: '幕後',
      copy: '第一張像樣的照片，從一個產品開始。\n光、紙、一隻手 ── 就這麼簡單。',
      asset: 'ink-stone.svg (1080×1920)',
      cta: 'swipe up' },
    { day: 5, weekday: '五', week: 'W1', channel: 'IG', format: 'Feed (4:5)', theme: 'opening',
      title: '我們聽到了',
      copy: '「東西明明很好，但照片拍不漂亮。」\n── 阿婆ㄟ切仔麵店\n\n這句話，我們在過去三年聽過 47 次。\n所以我們做「好物・好照」。',
      asset: 'still-bowl-rice.svg (1080×1350)',
      cta: 'tap @3q.hatchery' },
    { day: 6, weekday: '六', week: 'W1', channel: 'THREADS', format: 'Text', theme: 'opening',
      title: '手記 · 01',
      copy: '一張像樣的照片，\n是一間店被陌生人\n看見的第一個機會。\n\n── 孵化所手記',
      asset: 'text-only',
      cta: '' },
    { day: 7, weekday: '日', week: 'W1', channel: 'IG-STORY', format: 'Story', theme: 'opening',
      title: '週日靜物',
      copy: '一週的休息，從一張不擺拍的桌面開始。',
      asset: 'raw-linen.svg (1080×1920)',
      cta: 'see you Monday' },

    // ===== WEEK 2 — 誰已經來了 =====
    { day: 8, weekday: '一', week: 'W2', channel: 'LINE', format: 'Carousel Push', theme: 'portfolio',
      title: '入駐 02 · 三代米舖',
      copy: '台南。米賣到第三代。\n爺爺、爸爸、女兒，三雙手。\n我們做的，不是把它變新 ── 是把它的好擦亮。',
      asset: 'rice-stalk.svg + 3 cards',
      cta: '回「02 三代米舖」看完整故事' },
    { day: 9, weekday: '二', week: 'W2', channel: 'IG-STORY', format: 'Story', theme: 'portfolio',
      title: '02 · 從爺爺的木櫃開始',
      copy: '第一個動作，不是拍米。\n是把那個傳了 40 年的木櫃，先擦乾淨。',
      asset: 'cupped-palm-light.svg' },
    { day: 10, weekday: '三', week: 'W2', channel: 'IG', format: 'Feed (4:5)', theme: 'portfolio',
      title: 'NO. 02 · 三代米舖',
      copy: '「不要變太多。」\n── 爺爺說。\n\n所以我們先什麼都不換。\n只是把每一袋米的名字，認真寫了一次。',
      asset: 'rice-stalk.svg (1080×1350)' },
    { day: 11, weekday: '四', week: 'W2', channel: 'IG-STORY', format: 'Story', theme: 'portfolio',
      title: '工序 · 包裝重排',
      copy: '同一張紙袋，字體換了，米的等級反而看得更清楚。',
      asset: 'envelope-flat.svg' },
    { day: 12, weekday: '五', week: 'W2', channel: 'IG', format: 'Feed (4:5)', theme: 'portfolio',
      title: '我們聽到了 · 02',
      copy: '「想更新，但怕老客人覺得『變了』。」\n── 三代米舖\n\n所以我們的更新，是擦亮，不是換掉。\n老客人不會生氣，新客人會走進來。',
      asset: 'rice-stalk.svg (1080×1350)' },
    { day: 13, weekday: '六', week: 'W2', channel: 'TIKTOK', format: 'Cover (1080×1920)', theme: 'portfolio',
      title: 'EP. 02 · 米的三代',
      copy: '60 秒。\n從一袋米的名字，講到三代人的手。',
      asset: 'rice-stalk.svg (1080×1920)' },
    { day: 14, weekday: '日', week: 'W2', channel: 'THREADS', format: 'Text', theme: 'portfolio',
      title: '手記 · 02',
      copy: '不是把它變新。\n是把它的好擦亮。\n\n── 孵化所手記' },

    // ===== WEEK 3 — 我們做了什麼 =====
    { day: 15, weekday: '一', week: 'W3', channel: 'LINE', format: 'Carousel Push', theme: 'process',
      title: '好物・好照 · 工序公開',
      copy: '500 元一張，從來不是「便宜的照片」。\n是「一個產品被看見的最低成本」。\n往右滑，看 4 個工序步驟。',
      asset: '4 process cards' },
    { day: 16, weekday: '二', week: 'W3', channel: 'IG-STORY', format: 'Story', theme: 'process',
      title: '步驟 01 · 聽',
      copy: '第一件事不是拍。\n是聽你 30 分鐘，講這個產品的來歷。',
      asset: 'cupped-palm-light.svg' },
    { day: 17, weekday: '三', week: 'W3', channel: 'IG', format: 'Feed (4:5)', theme: 'process',
      title: '一張照片，三個小時',
      copy: '光要等。\n位置要試。\n背景要素 — 紙、布、木頭 — 一樣一樣換。\n\n500 元，買的不是按下快門那一秒。\n買的是這三個小時。',
      asset: 'ink-stone.svg (1080×1350)' },
    { day: 18, weekday: '四', week: 'W3', channel: 'IG-STORY', format: 'Story', theme: 'process',
      title: '步驟 02 · 一張紙',
      copy: '我們從來不用塑膠背景。\n一張米紙、一塊麻、一片木 ── 台灣本來就有的材料。' },
    { day: 19, weekday: '五', week: 'W3', channel: 'IG', format: 'Feed (4:5)', theme: 'process',
      title: '「陪你被看見」是什麼意思',
      copy: '不是接案。\n是 90 天，每週一次的線上會。\n我們替你看：招牌、菜單、上週貼了什麼、下週要做什麼。\n\n像有一個編輯陪你跑一季。',
      asset: 'envelope-flat.svg (1080×1350)' },
    { day: 20, weekday: '六', week: 'W3', channel: 'IG-STORY', format: 'Story', theme: 'process',
      title: '工作室一角',
      copy: '一張木桌、一台 Hasselblad、一盞燈。\n夠了。',
      asset: 'raw-linen.svg' },
    { day: 21, weekday: '日', week: 'W3', channel: 'THREADS', format: 'Text', theme: 'process',
      title: '手記 · 03',
      copy: '東西好，會說話。\n我們只是負責\n替它把音量調對。\n\n── 孵化所手記' },

    // ===== WEEK 4 — 下一個會是誰 =====
    { day: 22, weekday: '一', week: 'W4', channel: 'LINE', format: 'Carousel Push', theme: 'invitation',
      title: '下一批入駐 · 開放諮詢',
      copy: '4 月入駐，現在開放諮詢。\n3 個免費諮詢時段 / 週。\n回「諮詢」我們開時段。',
      asset: '4 invitation cards',
      cta: '回「諮詢」' },
    { day: 23, weekday: '二', week: 'W4', channel: 'IG-STORY', format: 'Story', theme: 'invitation',
      title: '誰可以申請',
      copy: '・在台灣的小品牌\n・有產品、有故事、有口味\n・店多大多小都可以',
      asset: 'cupped-palm-light.svg' },
    { day: 24, weekday: '三', week: 'W4', channel: 'IG', format: 'Feed (4:5)', theme: 'invitation',
      title: '你以為的小，是別人眼中的專注',
      copy: '一個攤位、一個品項、一個你自己照顧的店 ──\n那不是小，那是專注。\n\n我們替專注的人做事。',
      asset: 'still-bowl-rice.svg (1080×1350)' },
    { day: 25, weekday: '四', week: 'W4', channel: 'IG-STORY', format: 'Story', theme: 'invitation',
      title: '申請方式',
      copy: 'LINE @121LKSPE\n回「說說我的店」\n我們會引導你完成 8 個問題。',
      asset: 'envelope-flat.svg' },
    { day: 26, weekday: '五', week: 'W4', channel: 'IG', format: 'Feed (4:5)', theme: 'invitation',
      title: '客戶聲音 · 收尾',
      copy: '「我以為我做的太小，沒有資格被孵化。」\n── 一個剛報名的麵包師傅\n\n我們的回答：\n沒有東西「太小」。\n只有「還沒被好好看見」。',
      asset: 'raw-linen.svg (1080×1350)' },
    { day: 27, weekday: '六', week: 'W4', channel: 'TIKTOK', format: 'Cover (1080×1920)', theme: 'invitation',
      title: 'EP. 04 · 下一個',
      copy: '60 秒，講為什麼下一個應該是你。' },
    { day: 28, weekday: '日', week: 'W4', channel: 'THREADS', format: 'Text', theme: 'invitation',
      title: '手記 · 04',
      copy: '招牌不是裝飾。\n是邀請函。\n\n── 孵化所手記' },

    // bonus footnote days
    { day: 29, weekday: '一', week: 'W4+', channel: 'LINE', format: 'Push', theme: 'invitation',
      title: '本月入駐回顧 + 下月預告',
      copy: '本月入駐 4 個品牌的成果回顧 + 下月的預告。\n回「下個月」看新名單。' },
    { day: 30, weekday: '二', week: 'W4+', channel: 'IG', format: 'Feed (1:1)', theme: 'invitation',
      title: '謝謝你願意說',
      copy: '一個月。\n4 個入駐品牌。\n12 篇貼文。\n27 個新諮詢。\n\n謝謝你願意說。\n下個月見。',
      asset: 'cupped-palm-light.svg (1080×1080)' },
  ],
};
